CREATE SCHEMA DB_PRODUCTOS;
USE DB_PRODUCTOS;

CREATE TABLE PRODUCTO(
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  PRECIO DECIMAL(8, 2) NOT NULL  -- DECIMAL(8,2) = MAX DEC 123.456,78
);

INSERT INTO PRODUCTO(NOMBRE, PRECIO) VALUES
('Llaves de la Moncloa', 7),
('Pulpo', 25),
('Mansión en Waterloo', 59000.58),
('Uvas con Vito Quiles', 43.98);
